"""unified baseline in blog/shop schema

Revision ID: 0001_unified_baseline
Revises: 
Create Date: 2026-06-06 18:44:14.183810

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '0001_unified_baseline'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=100), nullable=False),
    sa.Column('slugs', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('attributes', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['blog.categories.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='blog'
    )
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_blog_categories_code'), ['code'], unique=True)
        batch_op.create_index(batch_op.f('ix_blog_categories_is_active'), ['is_active'], unique=False)

    op.create_table('homepage_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('button_text', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('about_section', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('pause_on_hover', sa.Boolean(), nullable=True),
    sa.Column('lazy_loading', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='blog'
    )
    op.create_table('homepage_slides',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slide_id', sa.String(length=100), nullable=False),
    sa.Column('image_url', sa.String(length=500), nullable=False),
    sa.Column('alt_text', sa.String(length=200), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('subtitles', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('cta_url', sa.String(length=500), nullable=True),
    sa.Column('cta_text', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('cta_new_tab', sa.Boolean(), nullable=True),
    sa.Column('autoplay_delay', sa.Integer(), nullable=True),
    sa.Column('video_url', sa.String(length=500), nullable=True),
    sa.Column('media_type', sa.String(length=20), nullable=True),
    sa.Column('focal_point', sa.String(length=30), nullable=True),
    sa.Column('overlay_opacity', sa.Integer(), nullable=True),
    sa.Column('titles', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('start_date', sa.DateTime(), nullable=True),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slide_id'),
    schema='blog'
    )
    op.create_table('menus',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('location', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='blog'
    )
    op.create_table('permissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=100), nullable=False),
    sa.Column('name', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('description', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('module', sa.String(length=50), nullable=False),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='blog'
    )
    with op.batch_alter_table('permissions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_blog_permissions_code'), ['code'], unique=True)
        batch_op.create_index(batch_op.f('ix_blog_permissions_module'), ['module'], unique=False)

    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('description', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_system', sa.Boolean(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('permissions_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='blog'
    )
    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_blog_roles_code'), ['code'], unique=True)
        batch_op.create_index(batch_op.f('ix_blog_roles_is_active'), ['is_active'], unique=False)

    op.create_table('settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('data_type', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='blog'
    )
    with op.batch_alter_table('settings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_blog_settings_key'), ['key'], unique=True)

    op.create_table('submissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('submission_type', sa.String(length=50), nullable=True),
    sa.Column('character_name', sa.String(length=100), nullable=True),
    sa.Column('birth_year', sa.String(length=4), nullable=True),
    sa.Column('birth_month', sa.String(length=2), nullable=True),
    sa.Column('birth_day', sa.String(length=2), nullable=True),
    sa.Column('birth_time', sa.String(length=50), nullable=True),
    sa.Column('birth_place', sa.String(length=100), nullable=True),
    sa.Column('question', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('admin_notes', sa.Text(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('attributes', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='blog'
    )
    with op.batch_alter_table('submissions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_blog_submissions_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_blog_submissions_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_blog_submissions_submission_type'), ['submission_type'], unique=False)

    op.create_table('tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('slugs', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('attributes', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='blog'
    )
    with op.batch_alter_table('tags', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_blog_tags_code'), ['code'], unique=True)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('avatar', sa.String(length=500), nullable=True),
    sa.Column('attributes', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('meta_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='blog'
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_blog_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_blog_users_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_blog_users_username'), ['username'], unique=True)

    op.create_table('payment_methods',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('description', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('supported_currencies', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='shop'
    )
    with op.batch_alter_table('payment_methods', schema='shop') as batch_op:
        batch_op.create_index(batch_op.f('ix_shop_payment_methods_code'), ['code'], unique=True)
        batch_op.create_index(batch_op.f('ix_shop_payment_methods_is_active'), ['is_active'], unique=False)

    op.create_table('activity_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('table_name', sa.String(length=50), nullable=True),
    sa.Column('record_id', sa.Integer(), nullable=True),
    sa.Column('old_values', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('new_values', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['blog.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='blog'
    )
    with op.batch_alter_table('activity_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_blog_activity_logs_created_at'), ['created_at'], unique=False)

    op.create_table('contents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('slug', sa.String(length=200), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('content_type', sa.String(length=50), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('author_id', sa.Integer(), nullable=True),
    sa.Column('featured_image', sa.String(length=500), nullable=True),
    sa.Column('cover_image', sa.String(length=500), nullable=True),
    sa.Column('meta_title', sa.String(length=200), nullable=True),
    sa.Column('meta_description', sa.Text(), nullable=True),
    sa.Column('views_count', sa.Integer(), nullable=True),
    sa.Column('likes_count', sa.Integer(), nullable=True),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('language', sa.String(length=10), nullable=False),
    sa.Column('original_id', sa.Integer(), nullable=True),
    sa.Column('attributes', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('meta_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['blog.users.id'], ),
    sa.ForeignKeyConstraint(['category_id'], ['blog.categories.id'], ),
    sa.ForeignKeyConstraint(['original_id'], ['blog.contents.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='blog'
    )
    with op.batch_alter_table('contents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_blog_contents_author_id'), ['author_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_blog_contents_category_id'), ['category_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_blog_contents_content_type'), ['content_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_blog_contents_language'), ['language'], unique=False)
        batch_op.create_index(batch_op.f('ix_blog_contents_published_at'), ['published_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_blog_contents_slug'), ['slug'], unique=True)
        batch_op.create_index(batch_op.f('ix_blog_contents_status'), ['status'], unique=False)
        batch_op.create_index('ix_contents_list', ['status', 'content_type', 'language', 'published_at'], unique=False)

    op.create_table('role_permissions',
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('permission_id', sa.Integer(), nullable=False),
    sa.Column('granted_at', sa.DateTime(), nullable=True),
    sa.Column('granted_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['granted_by'], ['blog.users.id'], ),
    sa.ForeignKeyConstraint(['permission_id'], ['blog.permissions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['blog.roles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('role_id', 'permission_id'),
    schema='blog'
    )
    op.create_table('user_roles',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('assigned_at', sa.DateTime(), nullable=True),
    sa.Column('assigned_by', sa.Integer(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['blog.roles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['blog.users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'role_id'),
    schema='blog'
    )
    op.create_table('orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_no', sa.String(length=50), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('items', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('language', sa.String(length=10), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('payment_method', sa.String(length=50), nullable=True),
    sa.Column('attributes', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('paid_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['blog.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='shop'
    )
    with op.batch_alter_table('orders', schema='shop') as batch_op:
        batch_op.create_index(batch_op.f('ix_shop_orders_currency'), ['currency'], unique=False)
        batch_op.create_index(batch_op.f('ix_shop_orders_order_no'), ['order_no'], unique=True)
        batch_op.create_index(batch_op.f('ix_shop_orders_payment_method'), ['payment_method'], unique=False)
        batch_op.create_index(batch_op.f('ix_shop_orders_status'), ['status'], unique=False)

    op.create_table('comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('author_name', sa.String(length=100), nullable=True),
    sa.Column('author_email', sa.String(length=100), nullable=True),
    sa.Column('comment_text', sa.Text(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['content_id'], ['blog.contents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_id'], ['blog.comments.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['blog.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='blog'
    )
    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_blog_comments_status'), ['status'], unique=False)

    op.create_table('content_tags',
    sa.Column('content_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['content_id'], ['blog.contents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['blog.tags.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('content_id', 'tag_id'),
    schema='blog'
    )
    op.create_table('menu_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('menu_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('url', sa.String(length=500), nullable=True),
    sa.Column('content_id', sa.Integer(), nullable=True),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.Column('css_class', sa.String(length=100), nullable=True),
    sa.Column('target', sa.String(length=20), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['content_id'], ['blog.contents.id'], ),
    sa.ForeignKeyConstraint(['menu_id'], ['blog.menus.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_id'], ['blog.menu_items.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='blog'
    )
    op.create_table('products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.String(length=100), nullable=False),
    sa.Column('names', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('descriptions', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('short_descriptions', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('original_price', sa.Integer(), nullable=True),
    sa.Column('stock_quantity', sa.Integer(), nullable=True),
    sa.Column('stock_status', sa.String(length=20), nullable=True),
    sa.Column('featured_image', sa.String(length=500), nullable=True),
    sa.Column('gallery_images', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_featured', sa.Boolean(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.Column('meta_title', sa.String(length=200), nullable=True),
    sa.Column('meta_description', sa.Text(), nullable=True),
    sa.Column('views_count', sa.Integer(), nullable=True),
    sa.Column('sales_count', sa.Integer(), nullable=True),
    sa.Column('detail_content_id', sa.Integer(), nullable=True),
    sa.Column('language', sa.String(length=10), nullable=False),
    sa.Column('original_id', sa.Integer(), nullable=True),
    sa.Column('attributes', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('meta_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['blog.categories.id'], ),
    sa.ForeignKeyConstraint(['detail_content_id'], ['blog.contents.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['original_id'], ['shop.products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('product_id', 'language', name='uq_product_id_language'),
    schema='shop'
    )
    with op.batch_alter_table('products', schema='shop') as batch_op:
        batch_op.create_index(batch_op.f('ix_shop_products_category_id'), ['category_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_shop_products_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_shop_products_language'), ['language'], unique=False)
        batch_op.create_index(batch_op.f('ix_shop_products_product_id'), ['product_id'], unique=False)

    op.create_table('product_prices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('original_price', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['shop.products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('product_id', 'currency', name='uq_product_currency'),
    schema='shop'
    )
    with op.batch_alter_table('product_prices', schema='shop') as batch_op:
        batch_op.create_index(batch_op.f('ix_shop_product_prices_currency'), ['currency'], unique=False)
        batch_op.create_index(batch_op.f('ix_shop_product_prices_is_active'), ['is_active'], unique=False)

    op.create_table('product_tags',
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['shop.products.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['blog.tags.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('product_id', 'tag_id'),
    schema='shop'
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('product_tags', schema='shop')
    with op.batch_alter_table('product_prices', schema='shop') as batch_op:
        batch_op.drop_index(batch_op.f('ix_shop_product_prices_is_active'))
        batch_op.drop_index(batch_op.f('ix_shop_product_prices_currency'))

    op.drop_table('product_prices', schema='shop')
    with op.batch_alter_table('products', schema='shop') as batch_op:
        batch_op.drop_index(batch_op.f('ix_shop_products_product_id'))
        batch_op.drop_index(batch_op.f('ix_shop_products_language'))
        batch_op.drop_index(batch_op.f('ix_shop_products_is_active'))
        batch_op.drop_index(batch_op.f('ix_shop_products_category_id'))

    op.drop_table('products', schema='shop')
    op.drop_table('menu_items', schema='blog')
    op.drop_table('content_tags', schema='blog')
    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_blog_comments_status'))

    op.drop_table('comments', schema='blog')
    with op.batch_alter_table('orders', schema='shop') as batch_op:
        batch_op.drop_index(batch_op.f('ix_shop_orders_status'))
        batch_op.drop_index(batch_op.f('ix_shop_orders_payment_method'))
        batch_op.drop_index(batch_op.f('ix_shop_orders_order_no'))
        batch_op.drop_index(batch_op.f('ix_shop_orders_currency'))

    op.drop_table('orders', schema='shop')
    op.drop_table('user_roles', schema='blog')
    op.drop_table('role_permissions', schema='blog')
    with op.batch_alter_table('contents', schema=None) as batch_op:
        batch_op.drop_index('ix_contents_list')
        batch_op.drop_index(batch_op.f('ix_blog_contents_status'))
        batch_op.drop_index(batch_op.f('ix_blog_contents_slug'))
        batch_op.drop_index(batch_op.f('ix_blog_contents_published_at'))
        batch_op.drop_index(batch_op.f('ix_blog_contents_language'))
        batch_op.drop_index(batch_op.f('ix_blog_contents_content_type'))
        batch_op.drop_index(batch_op.f('ix_blog_contents_category_id'))
        batch_op.drop_index(batch_op.f('ix_blog_contents_author_id'))

    op.drop_table('contents', schema='blog')
    with op.batch_alter_table('activity_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_blog_activity_logs_created_at'))

    op.drop_table('activity_logs', schema='blog')
    with op.batch_alter_table('payment_methods', schema='shop') as batch_op:
        batch_op.drop_index(batch_op.f('ix_shop_payment_methods_is_active'))
        batch_op.drop_index(batch_op.f('ix_shop_payment_methods_code'))

    op.drop_table('payment_methods', schema='shop')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_blog_users_username'))
        batch_op.drop_index(batch_op.f('ix_blog_users_is_active'))
        batch_op.drop_index(batch_op.f('ix_blog_users_email'))

    op.drop_table('users', schema='blog')
    with op.batch_alter_table('tags', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_blog_tags_code'))

    op.drop_table('tags', schema='blog')
    with op.batch_alter_table('submissions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_blog_submissions_submission_type'))
        batch_op.drop_index(batch_op.f('ix_blog_submissions_status'))
        batch_op.drop_index(batch_op.f('ix_blog_submissions_created_at'))

    op.drop_table('submissions', schema='blog')
    with op.batch_alter_table('settings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_blog_settings_key'))

    op.drop_table('settings', schema='blog')
    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_blog_roles_is_active'))
        batch_op.drop_index(batch_op.f('ix_blog_roles_code'))

    op.drop_table('roles', schema='blog')
    with op.batch_alter_table('permissions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_blog_permissions_module'))
        batch_op.drop_index(batch_op.f('ix_blog_permissions_code'))

    op.drop_table('permissions', schema='blog')
    op.drop_table('menus', schema='blog')
    op.drop_table('homepage_slides', schema='blog')
    op.drop_table('homepage_settings', schema='blog')
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_blog_categories_is_active'))
        batch_op.drop_index(batch_op.f('ix_blog_categories_code'))

    op.drop_table('categories', schema='blog')
    # ### end Alembic commands ###
