"""Initial migration

Revision ID: b9a6821ec682
Revises: 
Create Date: 2026-01-28 01:32:26.181005

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b9a6821ec682'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activity_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_activity_logs_created_at'))
        batch_op.drop_index(batch_op.f('idx_activity_logs_table_name'))
        batch_op.drop_index(batch_op.f('idx_activity_logs_user_id'))
        batch_op.create_index(batch_op.f('ix_activity_logs_created_at'), ['created_at'], unique=False)

    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('categories_code_key'), type_='unique')
        batch_op.drop_index(batch_op.f('idx_categories_code'))
        batch_op.drop_index(batch_op.f('idx_categories_is_active'))
        batch_op.drop_index(batch_op.f('idx_categories_parent_id'))
        batch_op.create_index(batch_op.f('ix_categories_code'), ['code'], unique=True)
        batch_op.create_index(batch_op.f('ix_categories_is_active'), ['is_active'], unique=False)

    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_comments_content_id'))
        batch_op.drop_index(batch_op.f('idx_comments_status'))
        batch_op.create_index(batch_op.f('ix_comments_status'), ['status'], unique=False)

    with op.batch_alter_table('contents', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('contents_slug_key'), type_='unique')
        batch_op.drop_index(batch_op.f('idx_contents_attributes'), postgresql_using='gin')
        batch_op.drop_index(batch_op.f('idx_contents_author_id'))
        batch_op.drop_index(batch_op.f('idx_contents_category_id'))
        batch_op.drop_index(batch_op.f('idx_contents_content_type'))
        batch_op.drop_index(batch_op.f('idx_contents_language'))
        batch_op.drop_index(batch_op.f('idx_contents_published_at'))
        batch_op.drop_index(batch_op.f('idx_contents_slug'))
        batch_op.drop_index(batch_op.f('idx_contents_status'))
        batch_op.create_index(batch_op.f('ix_contents_author_id'), ['author_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_contents_category_id'), ['category_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_contents_content_type'), ['content_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_contents_language'), ['language'], unique=False)
        batch_op.create_index(batch_op.f('ix_contents_published_at'), ['published_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_contents_slug'), ['slug'], unique=True)
        batch_op.create_index(batch_op.f('ix_contents_status'), ['status'], unique=False)

    with op.batch_alter_table('media', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_media_folder_id'))
        batch_op.drop_index(batch_op.f('idx_media_uploaded_by'))

    with op.batch_alter_table('menu_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_menu_items_menu_id'))

    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_orders_currency'))
        batch_op.drop_index(batch_op.f('idx_orders_order_no'))
        batch_op.drop_index(batch_op.f('idx_orders_status'))
        batch_op.drop_index(batch_op.f('idx_orders_user_id'))
        batch_op.drop_constraint(batch_op.f('orders_order_no_key'), type_='unique')
        batch_op.create_index(batch_op.f('ix_orders_currency'), ['currency'], unique=False)
        batch_op.create_index(batch_op.f('ix_orders_order_no'), ['order_no'], unique=True)
        batch_op.create_index(batch_op.f('ix_orders_payment_method'), ['payment_method'], unique=False)
        batch_op.create_index(batch_op.f('ix_orders_status'), ['status'], unique=False)

    with op.batch_alter_table('payment_methods', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_payment_methods_code'))
        batch_op.drop_index(batch_op.f('idx_payment_methods_is_active'))
        batch_op.drop_constraint(batch_op.f('payment_methods_code_key'), type_='unique')
        batch_op.create_index(batch_op.f('ix_payment_methods_code'), ['code'], unique=True)
        batch_op.create_index(batch_op.f('ix_payment_methods_is_active'), ['is_active'], unique=False)

    with op.batch_alter_table('permissions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_permissions_code'))
        batch_op.drop_index(batch_op.f('idx_permissions_module'))
        batch_op.drop_constraint(batch_op.f('permissions_code_key'), type_='unique')
        batch_op.create_index(batch_op.f('ix_permissions_code'), ['code'], unique=True)
        batch_op.create_index(batch_op.f('ix_permissions_module'), ['module'], unique=False)

    with op.batch_alter_table('product_prices', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_product_prices_currency'))
        batch_op.drop_index(batch_op.f('idx_product_prices_product_id'))
        batch_op.create_index(batch_op.f('ix_product_prices_currency'), ['currency'], unique=False)
        batch_op.create_index(batch_op.f('ix_product_prices_is_active'), ['is_active'], unique=False)

    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_products_attributes'), postgresql_using='gin')
        batch_op.drop_index(batch_op.f('idx_products_category_id'))
        batch_op.drop_index(batch_op.f('idx_products_is_active'))
        batch_op.drop_index(batch_op.f('idx_products_language'))
        batch_op.drop_index(batch_op.f('idx_products_product_id'))
        batch_op.create_index(batch_op.f('ix_products_category_id'), ['category_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_products_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_products_language'), ['language'], unique=False)
        batch_op.create_index(batch_op.f('ix_products_product_id'), ['product_id'], unique=False)

    with op.batch_alter_table('role_permissions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_role_permissions_permission_id'))
        batch_op.drop_index(batch_op.f('idx_role_permissions_role_id'))
        batch_op.create_foreign_key(None, 'users', ['granted_by'], ['id'])

    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_roles_code'))
        batch_op.drop_index(batch_op.f('idx_roles_is_active'))
        batch_op.drop_constraint(batch_op.f('roles_code_key'), type_='unique')
        batch_op.create_index(batch_op.f('ix_roles_code'), ['code'], unique=True)
        batch_op.create_index(batch_op.f('ix_roles_is_active'), ['is_active'], unique=False)

    with op.batch_alter_table('settings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_settings_key'))
        batch_op.drop_constraint(batch_op.f('settings_key_key'), type_='unique')
        batch_op.create_index(batch_op.f('ix_settings_key'), ['key'], unique=True)

    with op.batch_alter_table('submissions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_submissions_created_at'))
        batch_op.drop_index(batch_op.f('idx_submissions_status'))
        batch_op.drop_index(batch_op.f('idx_submissions_type'))
        batch_op.create_index(batch_op.f('ix_submissions_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_submissions_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_submissions_submission_type'), ['submission_type'], unique=False)

    with op.batch_alter_table('tags', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_tags_code'))
        batch_op.drop_constraint(batch_op.f('tags_code_key'), type_='unique')
        batch_op.create_index(batch_op.f('ix_tags_code'), ['code'], unique=True)

    with op.batch_alter_table('user_roles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_user_roles_role_id'))
        batch_op.drop_index(batch_op.f('idx_user_roles_user_id'))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_users_attributes'), postgresql_using='gin')
        batch_op.drop_index(batch_op.f('idx_users_email'))
        batch_op.drop_index(batch_op.f('idx_users_is_active'))
        batch_op.drop_index(batch_op.f('idx_users_role'))
        batch_op.drop_index(batch_op.f('idx_users_username'))
        batch_op.drop_constraint(batch_op.f('users_email_key'), type_='unique')
        batch_op.drop_constraint(batch_op.f('users_username_key'), type_='unique')
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))
        batch_op.drop_index(batch_op.f('ix_users_is_active'))
        batch_op.drop_index(batch_op.f('ix_users_email'))
        batch_op.create_unique_constraint(batch_op.f('users_username_key'), ['username'])
        batch_op.create_unique_constraint(batch_op.f('users_email_key'), ['email'])
        batch_op.create_index(batch_op.f('idx_users_username'), ['username'], unique=False)
        batch_op.create_index(batch_op.f('idx_users_role'), ['role'], unique=False)
        batch_op.create_index(batch_op.f('idx_users_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('idx_users_email'), ['email'], unique=False)
        batch_op.create_index(batch_op.f('idx_users_attributes'), ['attributes'], unique=False, postgresql_using='gin')

    with op.batch_alter_table('user_roles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_user_roles_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_user_roles_role_id'), ['role_id'], unique=False)

    with op.batch_alter_table('tags', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tags_code'))
        batch_op.create_unique_constraint(batch_op.f('tags_code_key'), ['code'])
        batch_op.create_index(batch_op.f('idx_tags_code'), ['code'], unique=False)

    with op.batch_alter_table('submissions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_submissions_submission_type'))
        batch_op.drop_index(batch_op.f('ix_submissions_status'))
        batch_op.drop_index(batch_op.f('ix_submissions_created_at'))
        batch_op.create_index(batch_op.f('idx_submissions_type'), ['submission_type'], unique=False)
        batch_op.create_index(batch_op.f('idx_submissions_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('idx_submissions_created_at'), ['created_at'], unique=False)

    with op.batch_alter_table('settings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_settings_key'))
        batch_op.create_unique_constraint(batch_op.f('settings_key_key'), ['key'])
        batch_op.create_index(batch_op.f('idx_settings_key'), ['key'], unique=False)

    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_roles_is_active'))
        batch_op.drop_index(batch_op.f('ix_roles_code'))
        batch_op.create_unique_constraint(batch_op.f('roles_code_key'), ['code'])
        batch_op.create_index(batch_op.f('idx_roles_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('idx_roles_code'), ['code'], unique=False)

    with op.batch_alter_table('role_permissions', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_index(batch_op.f('idx_role_permissions_role_id'), ['role_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_role_permissions_permission_id'), ['permission_id'], unique=False)

    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_products_product_id'))
        batch_op.drop_index(batch_op.f('ix_products_language'))
        batch_op.drop_index(batch_op.f('ix_products_is_active'))
        batch_op.drop_index(batch_op.f('ix_products_category_id'))
        batch_op.create_index(batch_op.f('idx_products_product_id'), ['product_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_products_language'), ['language'], unique=False)
        batch_op.create_index(batch_op.f('idx_products_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('idx_products_category_id'), ['category_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_products_attributes'), ['attributes'], unique=False, postgresql_using='gin')

    with op.batch_alter_table('product_prices', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_product_prices_is_active'))
        batch_op.drop_index(batch_op.f('ix_product_prices_currency'))
        batch_op.create_index(batch_op.f('idx_product_prices_product_id'), ['product_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_product_prices_currency'), ['currency'], unique=False)

    with op.batch_alter_table('permissions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_permissions_module'))
        batch_op.drop_index(batch_op.f('ix_permissions_code'))
        batch_op.create_unique_constraint(batch_op.f('permissions_code_key'), ['code'])
        batch_op.create_index(batch_op.f('idx_permissions_module'), ['module'], unique=False)
        batch_op.create_index(batch_op.f('idx_permissions_code'), ['code'], unique=False)

    with op.batch_alter_table('payment_methods', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_payment_methods_is_active'))
        batch_op.drop_index(batch_op.f('ix_payment_methods_code'))
        batch_op.create_unique_constraint(batch_op.f('payment_methods_code_key'), ['code'])
        batch_op.create_index(batch_op.f('idx_payment_methods_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('idx_payment_methods_code'), ['code'], unique=False)

    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_orders_status'))
        batch_op.drop_index(batch_op.f('ix_orders_payment_method'))
        batch_op.drop_index(batch_op.f('ix_orders_order_no'))
        batch_op.drop_index(batch_op.f('ix_orders_currency'))
        batch_op.create_unique_constraint(batch_op.f('orders_order_no_key'), ['order_no'])
        batch_op.create_index(batch_op.f('idx_orders_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_orders_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('idx_orders_order_no'), ['order_no'], unique=False)
        batch_op.create_index(batch_op.f('idx_orders_currency'), ['currency'], unique=False)

    with op.batch_alter_table('menu_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_menu_items_menu_id'), ['menu_id'], unique=False)

    with op.batch_alter_table('media', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_media_uploaded_by'), ['uploaded_by'], unique=False)
        batch_op.create_index(batch_op.f('idx_media_folder_id'), ['folder_id'], unique=False)

    with op.batch_alter_table('contents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_contents_status'))
        batch_op.drop_index(batch_op.f('ix_contents_slug'))
        batch_op.drop_index(batch_op.f('ix_contents_published_at'))
        batch_op.drop_index(batch_op.f('ix_contents_language'))
        batch_op.drop_index(batch_op.f('ix_contents_content_type'))
        batch_op.drop_index(batch_op.f('ix_contents_category_id'))
        batch_op.drop_index(batch_op.f('ix_contents_author_id'))
        batch_op.create_index(batch_op.f('idx_contents_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('idx_contents_slug'), ['slug'], unique=False)
        batch_op.create_index(batch_op.f('idx_contents_published_at'), ['published_at'], unique=False)
        batch_op.create_index(batch_op.f('idx_contents_language'), ['language'], unique=False)
        batch_op.create_index(batch_op.f('idx_contents_content_type'), ['content_type'], unique=False)
        batch_op.create_index(batch_op.f('idx_contents_category_id'), ['category_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_contents_author_id'), ['author_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_contents_attributes'), ['attributes'], unique=False, postgresql_using='gin')
        batch_op.create_unique_constraint(batch_op.f('contents_slug_key'), ['slug'])

    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_comments_status'))
        batch_op.create_index(batch_op.f('idx_comments_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('idx_comments_content_id'), ['content_id'], unique=False)

    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_categories_is_active'))
        batch_op.drop_index(batch_op.f('ix_categories_code'))
        batch_op.create_index(batch_op.f('idx_categories_parent_id'), ['parent_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_categories_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('idx_categories_code'), ['code'], unique=False)
        batch_op.create_unique_constraint(batch_op.f('categories_code_key'), ['code'])

    with op.batch_alter_table('activity_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_activity_logs_created_at'))
        batch_op.create_index(batch_op.f('idx_activity_logs_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_activity_logs_table_name'), ['table_name'], unique=False)
        batch_op.create_index(batch_op.f('idx_activity_logs_created_at'), ['created_at'], unique=False)

    # ### end Alembic commands ###
