"""core platform baseline —— 所有站台共用的平台資料表

Revision ID: 0001_core_baseline
Revises:

管理範圍：
    core/backend_engine/models.py 的 20 張表 + packages/media_lib 的 6 張表。
    這些是**平台**的表，每個站台都需要一份；站台自己的擴充表歸站台的 migration 鏈。

為什麼獨立成一條鏈：
    在此之前 core 的表由各站自己的 migration 建立，所以 core 模型改一個欄位就要
    手寫兩份 migration，沒有任何機制保證兩份一致 —— 這正是「改一次後端、所有
    站台一起改」在資料庫層不成立的地方。現在 core 改一次就在這條鏈寫一份。

schema 與索引名稱一律由環境變數推導，**不寫死**：
    站台可以把平台表放在 public（不設環境變數）或 blog/shop（Polaris 的做法），
    同一份 migration 通用。索引名稱跟著 schema 走，才能與 autogenerate 的
    命名慣例一致，否則每次比對都會冒出假的漂移。

對既有資料庫：
    Polaris / Claire 的平台表早已存在（由各自站台鏈建立）。upgrade() 偵測到
    就整條跳過，只記錄版本 —— 不需要人工 stamp。
"""
import os

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '0001_core_baseline'
down_revision = None
branch_labels = None
depends_on = None


# ── schema 佈局（與 core/backend_engine/models.py 讀同一組環境變數）──────────
BLOG = os.environ.get('OWS_BLOG_SCHEMA') or None
SHOP = os.environ.get('OWS_SHOP_SCHEMA') or None
try:
    from packages.media_lib.config import SCHEMA_NAME as MEDIA_LIB
except Exception:  # pragma: no cover
    MEDIA_LIB = 'media_lib'


# ── 身分模式（與 core/backend_engine/models.py 讀同一組環境變數）─────────────
# 使用者外鍵的目標與型別依部署而定：
#   local     站台自己的 users 表（Integer）
#   external  外部身分系統（BigInteger），例如 Polaris 指向紫微側的 account.app_users
#
# 這裡刻意讀環境變數而不是 import models —— migration 一旦寫下就該凍結，
# 跟著 models 走會讓「舊 migration 的意義隨新程式碼改變」，那是重現不了的 bug 溫床。
_IDENTITY_MODE = (os.environ.get('OWS_IDENTITY_MODE') or 'local').strip().lower()
_EXTERNAL_USER_TABLE = os.environ.get('OWS_EXTERNAL_USER_TABLE') or 'account.app_users'


def q(schema, rest):
    """把 'categories.id' 加上 schema 前綴；schema 為 None 時原樣回傳。"""
    return f'{schema}.{rest}' if schema else rest


def ix(schema, rest):
    """索引名稱：有 schema 時帶前綴，與 alembic 的命名慣例一致。"""
    return f'ix_{schema}_{rest}' if schema else f'ix_{rest}'


# 循環外鍵：files.folder_id → folders.id，而 folders.thumbnail_id → files.id。
# 建表時解不開，所以 folders 先不帶 thumbnail_id 的 FK，等 files 建好再補。
_FOLDER_THUMB_FK = 'folders_thumbnail_id_fkey'

_CORE_TABLES = ('contents', 'categories', 'settings', 'users')

if _IDENTITY_MODE == 'external':
    USER_ID_TYPE = sa.BigInteger()
    USER_FK = f'{_EXTERNAL_USER_TABLE}.id'
else:
    USER_ID_TYPE = sa.Integer()
    USER_FK = None  # 延後求值：需要 q(BLOG, ...)，見 _user_fk()


def _user_fk():
    """使用者外鍵目標。local 模式指向本鏈建立的 users 表。"""
    return USER_FK if USER_FK else q(BLOG, 'users.id')


def upgrade():
    bind = op.get_bind()
    for schema in {BLOG, SHOP, MEDIA_LIB} - {None}:
        op.execute(f'CREATE SCHEMA IF NOT EXISTS {schema}')

    # 冪等保護：Polaris / Claire 的平台表早在這條鏈存在之前就建好了（由各自的
    # 站台鏈）。偵測到就整條跳過、只記錄版本 —— 讓部署流程不需要「記得先 stamp」
    # 這種容易漏掉的人工步驟。空庫則照常建表。
    inspector = sa.inspect(bind)
    existing = set(inspector.get_table_names(schema=BLOG))
    present = existing & set(_CORE_TABLES)
    if present == set(_CORE_TABLES):
        return
    if present:
        raise RuntimeError(
            f"平台表只有部分存在：{sorted(present)}；"
            f"缺少 {sorted(set(_CORE_TABLES) - present)}。"
            "資料庫處於未預期的中間狀態，請人工確認後再繼續。"
        )

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=100), nullable=False),
    sa.Column('slugs', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('attributes', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], [q(BLOG, 'categories.id')], ),
    sa.PrimaryKeyConstraint('id'),
    schema=BLOG
    )
    with op.batch_alter_table('categories', schema=BLOG) as batch_op:
        batch_op.create_index(ix(BLOG, 'categories_code'), ['code'], unique=True)
        batch_op.create_index(ix(BLOG, 'categories_is_active'), ['is_active'], unique=False)

    op.create_table('homepage_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('button_text', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('about_section', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('pause_on_hover', sa.Boolean(), nullable=True),
    sa.Column('lazy_loading', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema=BLOG
    )
    op.create_table('homepage_slides',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slide_id', sa.String(length=100), nullable=False),
    sa.Column('image_url', sa.String(length=500), nullable=False),
    sa.Column('alt_text', sa.String(length=200), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('subtitles', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('cta_url', sa.String(length=500), nullable=True),
    sa.Column('cta_text', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('cta_new_tab', sa.Boolean(), nullable=True),
    sa.Column('autoplay_delay', sa.Integer(), nullable=True),
    sa.Column('video_url', sa.String(length=500), nullable=True),
    sa.Column('media_type', sa.String(length=20), nullable=True),
    sa.Column('focal_point', sa.String(length=30), nullable=True),
    sa.Column('overlay_opacity', sa.Integer(), nullable=True),
    sa.Column('titles', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('start_date', sa.DateTime(), nullable=True),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slide_id'),
    schema=BLOG
    )
    op.create_table('menus',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('location', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema=BLOG
    )
    op.create_table('permissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=100), nullable=False),
    sa.Column('name', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('description', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('module', sa.String(length=50), nullable=False),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema=BLOG
    )
    with op.batch_alter_table('permissions', schema=BLOG) as batch_op:
        batch_op.create_index(ix(BLOG, 'permissions_code'), ['code'], unique=True)
        batch_op.create_index(ix(BLOG, 'permissions_module'), ['module'], unique=False)

    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('description', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_system', sa.Boolean(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('permissions_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema=BLOG
    )
    with op.batch_alter_table('roles', schema=BLOG) as batch_op:
        batch_op.create_index(ix(BLOG, 'roles_code'), ['code'], unique=True)
        batch_op.create_index(ix(BLOG, 'roles_is_active'), ['is_active'], unique=False)

    op.create_table('settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('data_type', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema=BLOG
    )
    with op.batch_alter_table('settings', schema=BLOG) as batch_op:
        batch_op.create_index(ix(BLOG, 'settings_key'), ['key'], unique=True)

    op.create_table('submissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('submission_type', sa.String(length=50), nullable=True),
    sa.Column('character_name', sa.String(length=100), nullable=True),
    sa.Column('birth_year', sa.String(length=4), nullable=True),
    sa.Column('birth_month', sa.String(length=2), nullable=True),
    sa.Column('birth_day', sa.String(length=2), nullable=True),
    sa.Column('birth_time', sa.String(length=50), nullable=True),
    sa.Column('birth_place', sa.String(length=100), nullable=True),
    sa.Column('question', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('admin_notes', sa.Text(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('attributes', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema=BLOG
    )
    with op.batch_alter_table('submissions', schema=BLOG) as batch_op:
        batch_op.create_index(ix(BLOG, 'submissions_created_at'), ['created_at'], unique=False)
        batch_op.create_index(ix(BLOG, 'submissions_status'), ['status'], unique=False)
        batch_op.create_index(ix(BLOG, 'submissions_submission_type'), ['submission_type'], unique=False)

    op.create_table('tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('slugs', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('attributes', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema=BLOG
    )
    with op.batch_alter_table('tags', schema=BLOG) as batch_op:
        batch_op.create_index(ix(BLOG, 'tags_code'), ['code'], unique=True)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('avatar', sa.String(length=500), nullable=True),
    sa.Column('attributes', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('meta_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema=BLOG
    )
    with op.batch_alter_table('users', schema=BLOG) as batch_op:
        batch_op.create_index(ix(BLOG, 'users_email'), ['email'], unique=True)
        batch_op.create_index(ix(BLOG, 'users_is_active'), ['is_active'], unique=False)
        batch_op.create_index(ix(BLOG, 'users_username'), ['username'], unique=True)

    op.create_table('folders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('path', sa.String(length=500), nullable=False),
    sa.Column('created_by', USER_ID_TYPE, nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('thumbnail_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], [_user_fk()], deferrable=True),
    sa.ForeignKeyConstraint(['parent_id'], [q(MEDIA_LIB, 'folders.id')], ),
    sa.PrimaryKeyConstraint('id'),
    schema=MEDIA_LIB
    )
    with op.batch_alter_table('folders', schema=MEDIA_LIB) as batch_op:
        batch_op.create_index(ix(MEDIA_LIB, 'folders_path'), ['path'], unique=False)

    op.create_table('files',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('gcs_path', sa.String(length=500), nullable=False),
    sa.Column('public_url', sa.String(length=700), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('mime_type', sa.String(length=100), nullable=True),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('alt_text', sa.String(length=500), nullable=True),
    sa.Column('caption', sa.Text(), nullable=True),
    sa.Column('folder_id', sa.Integer(), nullable=True),
    sa.Column('uploaded_by', USER_ID_TYPE, nullable=True),
    sa.Column('attributes', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['folder_id'], [q(MEDIA_LIB, 'folders.id')], ),
    sa.ForeignKeyConstraint(['uploaded_by'], [_user_fk()], deferrable=True),
    sa.PrimaryKeyConstraint('id'),
    schema=MEDIA_LIB
    )
    with op.batch_alter_table('files', schema=MEDIA_LIB) as batch_op:
        batch_op.create_index(ix(MEDIA_LIB, 'files_gcs_path'), ['gcs_path'], unique=False)

    op.create_foreign_key(
        _FOLDER_THUMB_FK, 'folders', 'files', ['thumbnail_id'], ['id'],
        source_schema=MEDIA_LIB, referent_schema=MEDIA_LIB,
    )

    op.create_table('tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('color', sa.String(length=7), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    schema=MEDIA_LIB
    )
    with op.batch_alter_table('tags', schema=MEDIA_LIB) as batch_op:
        batch_op.create_index(ix(MEDIA_LIB, 'tags_slug'), ['slug'], unique=True)

    op.create_table('payment_methods',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('description', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('supported_currencies', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema=SHOP
    )
    with op.batch_alter_table('payment_methods', schema=SHOP) as batch_op:
        batch_op.create_index(ix(SHOP, 'payment_methods_code'), ['code'], unique=True)
        batch_op.create_index(ix(SHOP, 'payment_methods_is_active'), ['is_active'], unique=False)

    op.create_table('activity_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', USER_ID_TYPE, nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('table_name', sa.String(length=50), nullable=True),
    sa.Column('record_id', sa.Integer(), nullable=True),
    sa.Column('old_values', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('new_values', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], [_user_fk()], ),
    sa.PrimaryKeyConstraint('id'),
    schema=BLOG
    )
    with op.batch_alter_table('activity_logs', schema=BLOG) as batch_op:
        batch_op.create_index(ix(BLOG, 'activity_logs_created_at'), ['created_at'], unique=False)

    op.create_table('contents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('slug', sa.String(length=200), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('content_type', sa.String(length=50), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('author_id', USER_ID_TYPE, nullable=True),
    sa.Column('featured_image', sa.String(length=500), nullable=True),
    sa.Column('cover_image', sa.String(length=500), nullable=True),
    sa.Column('meta_title', sa.String(length=200), nullable=True),
    sa.Column('meta_description', sa.Text(), nullable=True),
    sa.Column('views_count', sa.Integer(), nullable=True),
    sa.Column('likes_count', sa.Integer(), nullable=True),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('language', sa.String(length=10), nullable=False),
    sa.Column('original_id', sa.Integer(), nullable=True),
    sa.Column('attributes', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('meta_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], [_user_fk()], ),
    sa.ForeignKeyConstraint(['category_id'], [q(BLOG, 'categories.id')], ),
    sa.ForeignKeyConstraint(['original_id'], [q(BLOG, 'contents.id')], ),
    sa.PrimaryKeyConstraint('id'),
    schema=BLOG
    )
    with op.batch_alter_table('contents', schema=BLOG) as batch_op:
        batch_op.create_index(ix(BLOG, 'contents_author_id'), ['author_id'], unique=False)
        batch_op.create_index(ix(BLOG, 'contents_category_id'), ['category_id'], unique=False)
        batch_op.create_index(ix(BLOG, 'contents_content_type'), ['content_type'], unique=False)
        batch_op.create_index(ix(BLOG, 'contents_language'), ['language'], unique=False)
        batch_op.create_index(ix(BLOG, 'contents_published_at'), ['published_at'], unique=False)
        batch_op.create_index(ix(BLOG, 'contents_slug'), ['slug'], unique=True)
        batch_op.create_index(ix(BLOG, 'contents_status'), ['status'], unique=False)
        batch_op.create_index('ix_contents_list', ['status', 'content_type', 'language', 'published_at'], unique=False)

    op.create_table('role_permissions',
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('permission_id', sa.Integer(), nullable=False),
    sa.Column('granted_at', sa.DateTime(), nullable=True),
    sa.Column('granted_by', USER_ID_TYPE, nullable=True),
    sa.ForeignKeyConstraint(['granted_by'], [_user_fk()], ),
    sa.ForeignKeyConstraint(['permission_id'], [q(BLOG, 'permissions.id')], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], [q(BLOG, 'roles.id')], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('role_id', 'permission_id'),
    schema=BLOG
    )
    op.create_table('user_roles',
    sa.Column('user_id', USER_ID_TYPE, nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('assigned_at', sa.DateTime(), nullable=True),
    sa.Column('assigned_by', sa.Integer(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], [q(BLOG, 'roles.id')], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], [_user_fk()], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'role_id'),
    schema=BLOG
    )
    op.create_table('file_metadata',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('file_id', sa.Integer(), nullable=False),
    sa.Column('chart_id', sa.String(length=100), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('rating', sa.SmallInteger(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('source', sa.String(length=255), nullable=True),
    sa.Column('license', sa.String(length=100), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['file_id'], [q(MEDIA_LIB, 'files.id')], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema=MEDIA_LIB
    )
    with op.batch_alter_table('file_metadata', schema=MEDIA_LIB) as batch_op:
        batch_op.create_index(ix(MEDIA_LIB, 'file_metadata_chart_id'), ['chart_id'], unique=False)
        batch_op.create_index(ix(MEDIA_LIB, 'file_metadata_file_id'), ['file_id'], unique=True)

    op.create_table('file_tags',
    sa.Column('file_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['file_id'], [q(MEDIA_LIB, 'files.id')], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], [q(MEDIA_LIB, 'tags.id')], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('file_id', 'tag_id'),
    schema=MEDIA_LIB
    )
    op.create_table('file_variants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('file_id', sa.Integer(), nullable=False),
    sa.Column('variant_type', sa.String(length=20), nullable=False),
    sa.Column('gcs_path', sa.String(length=500), nullable=False),
    sa.Column('public_url', sa.String(length=700), nullable=False),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['file_id'], [q(MEDIA_LIB, 'files.id')], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema=MEDIA_LIB
    )
    with op.batch_alter_table('file_variants', schema=MEDIA_LIB) as batch_op:
        batch_op.create_index(ix(MEDIA_LIB, 'file_variants_file_id'), ['file_id'], unique=False)

    op.create_table('orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_no', sa.String(length=50), nullable=False),
    sa.Column('user_id', USER_ID_TYPE, nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('items', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('language', sa.String(length=10), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('payment_method', sa.String(length=50), nullable=True),
    sa.Column('attributes', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('paid_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], [_user_fk()], ),
    sa.PrimaryKeyConstraint('id'),
    schema=SHOP
    )
    with op.batch_alter_table('orders', schema=SHOP) as batch_op:
        batch_op.create_index(ix(SHOP, 'orders_currency'), ['currency'], unique=False)
        batch_op.create_index(ix(SHOP, 'orders_order_no'), ['order_no'], unique=True)
        batch_op.create_index(ix(SHOP, 'orders_payment_method'), ['payment_method'], unique=False)
        batch_op.create_index(ix(SHOP, 'orders_status'), ['status'], unique=False)

    op.create_table('comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content_id', sa.Integer(), nullable=False),
    sa.Column('user_id', USER_ID_TYPE, nullable=True),
    sa.Column('author_name', sa.String(length=100), nullable=True),
    sa.Column('author_email', sa.String(length=100), nullable=True),
    sa.Column('comment_text', sa.Text(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['content_id'], [q(BLOG, 'contents.id')], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_id'], [q(BLOG, 'comments.id')], ),
    sa.ForeignKeyConstraint(['user_id'], [_user_fk()], ),
    sa.PrimaryKeyConstraint('id'),
    schema=BLOG
    )
    with op.batch_alter_table('comments', schema=BLOG) as batch_op:
        batch_op.create_index(ix(BLOG, 'comments_status'), ['status'], unique=False)

    op.create_table('content_tags',
    sa.Column('content_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['content_id'], [q(BLOG, 'contents.id')], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], [q(BLOG, 'tags.id')], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('content_id', 'tag_id'),
    schema=BLOG
    )
    op.create_table('menu_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('menu_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('url', sa.String(length=500), nullable=True),
    sa.Column('content_id', sa.Integer(), nullable=True),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.Column('css_class', sa.String(length=100), nullable=True),
    sa.Column('target', sa.String(length=20), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['content_id'], [q(BLOG, 'contents.id')], ),
    sa.ForeignKeyConstraint(['menu_id'], [q(BLOG, 'menus.id')], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_id'], [q(BLOG, 'menu_items.id')], ),
    sa.PrimaryKeyConstraint('id'),
    schema=BLOG
    )
    op.create_table('products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.String(length=100), nullable=False),
    sa.Column('names', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('descriptions', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('short_descriptions', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('original_price', sa.Integer(), nullable=True),
    sa.Column('stock_quantity', sa.Integer(), nullable=True),
    sa.Column('stock_status', sa.String(length=20), nullable=True),
    sa.Column('featured_image', sa.String(length=500), nullable=True),
    sa.Column('gallery_images', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_featured', sa.Boolean(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.Column('meta_title', sa.String(length=200), nullable=True),
    sa.Column('meta_description', sa.Text(), nullable=True),
    sa.Column('views_count', sa.Integer(), nullable=True),
    sa.Column('sales_count', sa.Integer(), nullable=True),
    sa.Column('detail_content_id', sa.Integer(), nullable=True),
    sa.Column('language', sa.String(length=10), nullable=False),
    sa.Column('original_id', sa.Integer(), nullable=True),
    sa.Column('attributes', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('meta_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], [q(BLOG, 'categories.id')], ),
    sa.ForeignKeyConstraint(['detail_content_id'], [q(BLOG, 'contents.id')], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['original_id'], [q(SHOP, 'products.id')], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('product_id', 'language', name='uq_product_id_language'),
    schema=SHOP
    )
    with op.batch_alter_table('products', schema=SHOP) as batch_op:
        batch_op.create_index(ix(SHOP, 'products_category_id'), ['category_id'], unique=False)
        batch_op.create_index(ix(SHOP, 'products_is_active'), ['is_active'], unique=False)
        batch_op.create_index(ix(SHOP, 'products_language'), ['language'], unique=False)
        batch_op.create_index(ix(SHOP, 'products_product_id'), ['product_id'], unique=False)

    op.create_table('product_prices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('original_price', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], [q(SHOP, 'products.id')], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('product_id', 'currency', name='uq_product_currency'),
    schema=SHOP
    )
    with op.batch_alter_table('product_prices', schema=SHOP) as batch_op:
        batch_op.create_index(ix(SHOP, 'product_prices_currency'), ['currency'], unique=False)
        batch_op.create_index(ix(SHOP, 'product_prices_is_active'), ['is_active'], unique=False)

    op.create_table('product_tags',
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], [q(SHOP, 'products.id')], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], [q(BLOG, 'tags.id')], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('product_id', 'tag_id'),
    schema=SHOP
    )
    # ### end Alembic commands ###


def downgrade():
    if not (set(sa.inspect(op.get_bind()).get_table_names(schema=BLOG)) & set(_CORE_TABLES)):
        return
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('product_tags', schema=SHOP)
    with op.batch_alter_table('product_prices', schema=SHOP) as batch_op:
        batch_op.drop_index(ix(SHOP, 'product_prices_is_active'))
        batch_op.drop_index(ix(SHOP, 'product_prices_currency'))

    op.drop_table('product_prices', schema=SHOP)
    with op.batch_alter_table('products', schema=SHOP) as batch_op:
        batch_op.drop_index(ix(SHOP, 'products_product_id'))
        batch_op.drop_index(ix(SHOP, 'products_language'))
        batch_op.drop_index(ix(SHOP, 'products_is_active'))
        batch_op.drop_index(ix(SHOP, 'products_category_id'))

    op.drop_table('products', schema=SHOP)
    op.drop_table('menu_items', schema=BLOG)
    op.drop_table('content_tags', schema=BLOG)
    with op.batch_alter_table('comments', schema=BLOG) as batch_op:
        batch_op.drop_index(ix(BLOG, 'comments_status'))

    op.drop_table('comments', schema=BLOG)
    with op.batch_alter_table('orders', schema=SHOP) as batch_op:
        batch_op.drop_index(ix(SHOP, 'orders_status'))
        batch_op.drop_index(ix(SHOP, 'orders_payment_method'))
        batch_op.drop_index(ix(SHOP, 'orders_order_no'))
        batch_op.drop_index(ix(SHOP, 'orders_currency'))

    op.drop_table('orders', schema=SHOP)
    with op.batch_alter_table('file_variants', schema=MEDIA_LIB) as batch_op:
        batch_op.drop_index(ix(MEDIA_LIB, 'file_variants_file_id'))

    op.drop_table('file_variants', schema=MEDIA_LIB)
    op.drop_table('file_tags', schema=MEDIA_LIB)
    with op.batch_alter_table('file_metadata', schema=MEDIA_LIB) as batch_op:
        batch_op.drop_index(ix(MEDIA_LIB, 'file_metadata_file_id'))
        batch_op.drop_index(ix(MEDIA_LIB, 'file_metadata_chart_id'))

    op.drop_table('file_metadata', schema=MEDIA_LIB)
    op.drop_table('user_roles', schema=BLOG)
    op.drop_table('role_permissions', schema=BLOG)
    with op.batch_alter_table('contents', schema=BLOG) as batch_op:
        batch_op.drop_index('ix_contents_list')
        batch_op.drop_index(ix(BLOG, 'contents_status'))
        batch_op.drop_index(ix(BLOG, 'contents_slug'))
        batch_op.drop_index(ix(BLOG, 'contents_published_at'))
        batch_op.drop_index(ix(BLOG, 'contents_language'))
        batch_op.drop_index(ix(BLOG, 'contents_content_type'))
        batch_op.drop_index(ix(BLOG, 'contents_category_id'))
        batch_op.drop_index(ix(BLOG, 'contents_author_id'))

    op.drop_table('contents', schema=BLOG)
    with op.batch_alter_table('activity_logs', schema=BLOG) as batch_op:
        batch_op.drop_index(ix(BLOG, 'activity_logs_created_at'))

    op.drop_table('activity_logs', schema=BLOG)
    with op.batch_alter_table('payment_methods', schema=SHOP) as batch_op:
        batch_op.drop_index(ix(SHOP, 'payment_methods_is_active'))
        batch_op.drop_index(ix(SHOP, 'payment_methods_code'))

    op.drop_table('payment_methods', schema=SHOP)
    with op.batch_alter_table('tags', schema=MEDIA_LIB) as batch_op:
        batch_op.drop_index(ix(MEDIA_LIB, 'tags_slug'))

    op.drop_table('tags', schema=MEDIA_LIB)
    with op.batch_alter_table('folders', schema=MEDIA_LIB) as batch_op:
        batch_op.drop_index(ix(MEDIA_LIB, 'folders_path'))

    op.drop_table('folders', schema=MEDIA_LIB)
    with op.batch_alter_table('files', schema=MEDIA_LIB) as batch_op:
        batch_op.drop_index(ix(MEDIA_LIB, 'files_gcs_path'))

    op.drop_table('files', schema=MEDIA_LIB)
    with op.batch_alter_table('users', schema=BLOG) as batch_op:
        batch_op.drop_index(ix(BLOG, 'users_username'))
        batch_op.drop_index(ix(BLOG, 'users_is_active'))
        batch_op.drop_index(ix(BLOG, 'users_email'))

    op.drop_table('users', schema=BLOG)
    with op.batch_alter_table('tags', schema=BLOG) as batch_op:
        batch_op.drop_index(ix(BLOG, 'tags_code'))

    op.drop_table('tags', schema=BLOG)
    with op.batch_alter_table('submissions', schema=BLOG) as batch_op:
        batch_op.drop_index(ix(BLOG, 'submissions_submission_type'))
        batch_op.drop_index(ix(BLOG, 'submissions_status'))
        batch_op.drop_index(ix(BLOG, 'submissions_created_at'))

    op.drop_table('submissions', schema=BLOG)
    with op.batch_alter_table('settings', schema=BLOG) as batch_op:
        batch_op.drop_index(ix(BLOG, 'settings_key'))

    op.drop_table('settings', schema=BLOG)
    with op.batch_alter_table('roles', schema=BLOG) as batch_op:
        batch_op.drop_index(ix(BLOG, 'roles_is_active'))
        batch_op.drop_index(ix(BLOG, 'roles_code'))

    op.drop_table('roles', schema=BLOG)
    with op.batch_alter_table('permissions', schema=BLOG) as batch_op:
        batch_op.drop_index(ix(BLOG, 'permissions_module'))
        batch_op.drop_index(ix(BLOG, 'permissions_code'))

    op.drop_table('permissions', schema=BLOG)
    op.drop_table('menus', schema=BLOG)
    op.drop_table('homepage_slides', schema=BLOG)
    op.drop_table('homepage_settings', schema=BLOG)
    with op.batch_alter_table('categories', schema=BLOG) as batch_op:
        batch_op.drop_index(ix(BLOG, 'categories_is_active'))
        batch_op.drop_index(ix(BLOG, 'categories_code'))

    op.drop_table('categories', schema=BLOG)
    # ### end Alembic commands ###
